DROP TABLE IF EXISTS wcf1_cheat_database_entry;
CREATE TABLE wcf1_cheat_database_entry (
	entryID		INT(10)			NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID		INT(10)			NOT NULL DEFAULT 0,
	username	VARCHAR(255)		NOT NULL,
	pokedexNumber	INT(5)			NOT NULL,
	nickname	VARCHAR(255)		NOT NULL DEFAULT '',
	gender		TINYINT(1) USIGNED	NOT NULL DEFAULT 0,
	trainerName	VARCHAR(255)		NOT NULL,
	trainerID	INT(5) UNSIGNED		NOT NULL DEFAULT 0,
	level		TINYINT(3) UNSIGNED	NOT NULL DEFAULT 0,
	catchLocation	VARCHAR(255)		NOT NULL,
	catchDate	INT(10)			NOT NULL DEFAULT 0,
	catchLevel	TINYINT(3) UNSIGNED	NOT NULL DEFAULT 0,
	nature		TINYINT(3) UNSIGNED	NOT NULL,
	characteristic	TINYINT(3) UNSIGNED	NOT NULL,
	isShiny		TINYINT(1)		NOT NULL DEFAULT 0,
	ball		TINYINT(3) UNSIGNED	NOT NULL,
	ribbons		VARCHAR(255)		NOT NULL DEFAULT '',
	message		MEDIUMTEXT,
	FULLTEXT KEY (nickname, trainerName, message)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
